# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "笔记"
  pageRef = "categories/notes/"
  weight = 10

[[main]]
  name = "编程笔记"
  parent = "笔记"
  pageRef = "program"
  weight = 10

[[main]]
  name = "设计笔记"
  parent = "笔记"
  pageRef = "design"
  weight = 10

[[main]]
  name = "资源"
  pageRef = "categories/resources/"
  weight = 20

[[main]]
  name = "设计素材"
  parent = "资源"
  pageRef = "design-material"
  weight = 20

[[main]]
  name = "设计神器"
  parent = "资源"
  pageRef = "design-tool"
  weight = 20

[[main]]
  name = "日常"
  pageRef = "diary"
  weight = 30

[[main]]
  pre = "github"
  url = "https://github.com/cooloctopus/note.xxend.cool"
  weight = 40

[[subnavigation]]
  name = "标签"
  pageRef = "tags"
  weight = 10

[[subnavigation]]
  name = "分类"
  pageRef = "categories"
  weight = 20


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
  name = "标签"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "分类"
  pageRef = "categories"
  weight = 20
